### ISSUE TITLE
Metodo vector

### ISSUE THREAD

**Issue by abernalf** [Chinegua/IWVG.SwC.Chinegua#1]
Crear el método para crear un vector a partir de dos punto
[Mas info](https://github.com/Chinegua/IWVG.SwC.Chinegua/wiki/Documentaci%C3%B3n#class-coordenadas-vector)

**Comment by abernalf** [comment]
@raquelsr importante seguir las [pautas](https://github.com/Chinegua/IWVG.SwC.Chinegua/wiki/Practicas-a-seguir) para los comits y las ramas

**Comment by raquelsr** [comment]
Implementada la función según la descripción y subida al proyecto.
