### ISSUE TITLE
Nombres en mayusculas

### ISSUE THREAD

**Issue by abernalf** [Chinegua/IWVG.SwC.Chinegua#2]
Modificación en la clase User

[Más info](https://github.com/Chinegua/IWVG.SwC.Chinegua/wiki/Documentaci%C3%B3n#m%C3%A9todo-para-nombres-en-mayusculas-user)

**Comment by abernalf** [comment]
@jchantej importante seguir las [pautas](https://github.com/Chinegua/IWVG.SwC.Chinegua/wiki/Practicas-a-seguir) para los comits y las ramas

**Comment by Chinegua** [comment]
Hola @jchantej, esta noche cierra la fase 1 y solo queda esta mejora, algún problema?

**Comment by jchantej** [comment]
Creación del método que permite convertir en MAYUSCULAS una cadena de texto (Nombres y Apellidos)
