### ISSUE TITLE
Menor decimal

### ISSUE THREAD

**Issue by abernalf** [Chinegua/IWVG.SwC.Chinegua#3]
Metodo para buscar el menor decimal

[Mas info](https://github.com/Chinegua/IWVG.SwC.Chinegua/wiki/Documentaci%C3%B3n#m%C3%A9todo-para-poder-buscar-el-menor-decimal-decimal-collection)

**Comment by abernalf** [comment]
@DantDP importante seguir las [pautas](https://github.com/Chinegua/IWVG.SwC.Chinegua/wiki/Practicas-a-seguir) para los comits y las ramas

**Comment by DantDP** [comment]
@Chinegua he creado develop, y de ahí el issue#3, donde he modificado la clase. Luego he fusionado issue#3 con develop, y de ahí al master local, y a este le he hecho push con el master remoto. Después cierro issue#3 y develop.

**Comment by abernalf** [comment]
Está mal, solo hay que tocar la rama develop con sus respectivos issues, el arquitecto de proyecto es el que se encarga luego de hacer un release y añadirlo a la rama master @raquelsr @jchantej Vamos a esperar a que @DantDP solucione el problema.

P.D si necesitas ayuda avisa y nos ponemos

**Comment by abernalf** [comment]
Solucionado el problema de @DantDP, acordaos que como en clase, trabajaremos con la rama develop mediante issues, una vez todos tengan sus modificaciones en la rama develop, me encargaré de unirlo a la rama master mediante un release.

@raquelsr @jchantej

**Comment by abernalf** [comment]
@DantDP he reabierto el issue ya que como has puesto una excepción para este método hay que hacerle un test a la excepción, si no [Sonar](https://sonarcloud.io/component_measures?id=IWVG.SwC.Chinegua%3AIWVG.SwC.Chinegua&metric=new_coverage&selected=IWVG.SwC.Chinegua%3AIWVG.SwC.Chinegua%3Asrc%2Fmain%2Fjava%2FIWVG%2FSwC%2FChinegua%2Fcalculos%2FDecimalCollection.java) lo detecta como mal
