### ISSUE TITLE
Mayor numerador

### ISSUE THREAD

**Issue by abernalf** [Chinegua/IWVG.SwC.Chinegua#4]
Calcular si la fracción tiene numerador > denominador

**Comment by abernalf** [comment]
@DantDP importante seguir las [pautas](https://github.com/Chinegua/IWVG.SwC.Chinegua/wiki/Practicas-a-seguir) para los comits y las ramas

**Comment by DantDP** [comment]
He modificado la clase y probado el test correspondiente en issue#4, luego lo fusiono con develop, y hago push a develop.

**Comment by Chinegua** [comment]
Reabro issue por que no están las pruebas @DantDP

**Comment by abernalf** [comment]
Modificar las xpruebas para tener mayor coverage

**Comment by DantDP** [comment]
Ya lo he hecho
