### ISSUE TITLE
Suma de fracciones

### ISSUE THREAD

**Issue by abernalf** [Chinegua/IWVG.SwC.Chinegua#5]
Sumar dos fracciones

[Mas info](https://github.com/Chinegua/IWVG.SwC.Chinegua/wiki/Documentaci%C3%B3n#m%C3%A9todo-para-poder-sumar-dos-fraciones)

**Comment by abernalf** [comment]
@raquelsr importante seguir las [pautas](https://github.com/Chinegua/IWVG.SwC.Chinegua/wiki/Practicas-a-seguir) para los comits y las ramas

**Comment by raquelsr** [comment]
Resuelta la implementación de la suma de fracciones.
