### ISSUE TITLE
Multiplicacion de fracciones

### ISSUE THREAD

**Issue by abernalf** [Chinegua/IWVG.SwC.Chinegua#6]
Multiplicar ds fracciones

[Más info](https://github.com/Chinegua/IWVG.SwC.Chinegua/wiki/Documentaci%C3%B3n#m%C3%A9todo-para-multiplicar-fracciones)

**Comment by Chinegua** [comment]
@DantDP importante seguir las [pautas](https://github.com/Chinegua/IWVG.SwC.Chinegua/wiki/Practicas-a-seguir) para los comits y las ramas

**Comment by abernalf** [comment]
@jchantej importante seguir las [pautas](https://github.com/Chinegua/IWVG.SwC.Chinegua/wiki/Practicas-a-seguir) para los comits y las ramas

**Comment by jchantej** [comment]
Creando función que permite multiplicar dos fracciones las mismas que son pasadas como parametros.

**Comment by abernalf** [comment]
Tenemos que reabrir este issue por que no está completo, la etiqueta de sonar ha saltado por lo siguiente:
 * Bug: https://sonarcloud.io/project/issues?id=IWVG.SwC.Chinegua%3AIWVG.SwC.Chinegua&open=AV6a7dvrsnJZDvkaIuEB&resolved=false&types=BUG
 * Falta de pruebas: Hay que crear pruebas para que las asertions falle, aquí puedes verlo en sonarcloud para tener mas información: https://sonarcloud.io/component_measures?id=IWVG.SwC.Chinegua%3AIWVG.SwC.Chinegua&metric=new_coverage&selected=IWVG.SwC.Chinegua%3AIWVG.SwC.Chinegua%3Asrc%2Fmain%2Fjava%2FIWVG%2FSwC%2FChinegua%2Fcalculos%2FFraction.java

Una vez solucionado podemos cerrarlo

**Comment by abernalf** [comment]
Cerramos modificacion y te lo pongo en un issue nuevo @jchantej
