### ISSUE TITLE
Fix Sonar

### ISSUE THREAD

**Issue by abernalf** [Chinegua/IWVG.SwC.Chinegua#8]
Bug: https://sonarcloud.io/project/issues?id=IWVG.SwC.Chinegua%3AIWVG.SwC.Chinegua&open=AV6a7dvrsnJZDvkaIuEB&resolved=false&types=BUG
Falta de pruebas: Hay que crear pruebas para que las asertions falle, aquí puedes verlo en sonarcloud para tener mas información: https://sonarcloud.io/component_measures?id=IWVG.SwC.Chinegua%3AIWVG.SwC.Chinegua&metric=new_coverage&selected=IWVG.SwC.Chinegua%3AIWVG.SwC.Chinegua%3Asrc%2Fmain%2Fjava%2FIWVG%2FSwC%2FChinegua%2Fcalculos%2FFraction.java
Una vez solucionado podemos cerrarlo

**Comment by Chinegua** [comment]
Faltan los Bugs por solucionar, te adjunto link en Sonar para que los puedas ver @jchantej 
https://sonarcloud.io/project/issues?id=IWVG.SwC.Chinegua%3AIWVG.SwC.Chinegua&resolved=false&types=BUG

**Comment by abernalf** [comment]
Faltan los Bugs por solucionar, te adjunto link en Sonar para que los puedas ver @jchantej
https://sonarcloud.io/project/issues?id=IWVG.SwC.Chinegua%3AIWVG.SwC.Chinegua&resolved=false&types=BUG

**Comment by jchantej** [comment]
Correción de los Bugs Generados por SONARCLOUD.
